pmark_dial.in_file "standard"
pmark_dial.out_file "PART MARK"
pmark_dial.create 0
pmark_dial.for_main 1
pmark_dial.for_sec 1
pmark_dial.for_which_parts 1
pmark_dial.in_all_views 0
pmark_dial.OutOfPlane 1
pmark_dial.text_type 2
pmark_dial.text_colour 161
pmark_dial.frame_type 3
pmark_dial.line_colour 153
pmark_dial.Angle 0.000000
pmark_dial.ArrowType 0
pmark_dial.ArrowHeight 2.000000
pmark_dial.ArrowLength 2.500000
pmark_dial.height 3.000000
pmark_dial.default_size 0.000000
pmark_dial.mark_nsfs 0
pmark_dial.content_1 1
pmark_dial.flags 0
pmark_dial.mark_use_part_end 0
pmark_dial.ContentString1 "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><Element name="PART_POS" value="" subType="23"><Format font="Arial Narrow" color="161" height="3.000" hidden="0"/></Element></MarkPart></Mark>"
pmark_dial.ContentString2 "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><Element name="PART_POS" value="" subType="23"><Format font="Arial Narrow" color="161" height="3.000" hidden="0"/></Element></MarkPart></Mark>"
pmark_dial.ContentString3 "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><Element name="PART_POS" value="" subType="23"><Format font="Arial Narrow" color="161" height="3.000" hidden="0"/></Element></MarkPart></Mark>"
pmark_dial.ContentString4 "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><Element name="PART_POS" value="" subType="23"><Format font="Arial Narrow" color="161" height="3.000" hidden="0"/></Element></MarkPart></Mark>"
pmark_dial.ChamferContentString ""
pmark_dial.PourContentString "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><Element name="MATERIAL" value="" subType="10"><Format font="Arial" color="155" height="2.500"/></Element></MarkPart></Mark>"
pmark_dial.PourBreakContentString "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><UserText>POUR BREAK<Format font="Arial" color="155" height="2.500"/></UserText></MarkPart></Mark>"
pmark_dial.leader_line_type 0
pmark_dial.merge_dir 1
pmark_dial.MergeMarks 0
pmark_dial.CurrentContentTableNumber 0
pmark_dial.ForSubassMain 1
pmark_dial.ForSubassSecondary 1
pmark_dial.UseHiddenLines 1
pmark_dial.Rotation 0
pmark_dial.create_en 1
pmark_dial.for_main_en 1
pmark_dial.for_sec_en 1
pmark_dial.for_which_parts_en 1
pmark_dial.in_all_views_en 1
pmark_dial.OutOfPlane_en 1
pmark_dial.text_type_en 1
pmark_dial.text_colour_en 1
pmark_dial.frame_en 1
pmark_dial.line_colour_en 1
pmark_dial.Angle_en 1
pmark_dial.ArrowType_en 1
pmark_dial.ArrowHeight_en 1
pmark_dial.ArrowLength_en 1
pmark_dial.height_en 1
pmark_dial.content_en 1
pmark_dial.place_en 1
pmark_dial.default_size_en 1
pmark_dial.mark_nsfs_en 1
pmark_dial.use_part_end_en 1
pmark_dial.leader_line_type_en 1
pmark_dial.merge_dir_en 1
pmark_dial.MergeMarks_en 1
pmark_dial.ForSubassMain_en 1
pmark_dial.ForSubassSecondary_en 1
pmark_dial.UseHiddenLines_en 1
pmark_dial.Rotation_en 1
pmark_dial.txpl.text_placing_mode 1
pmark_dial.txpl.quarter_1 1
pmark_dial.txpl.quarter_2 2
pmark_dial.txpl.quarter_3 4
pmark_dial.txpl.quarter_4 8
pmark_dial.txpl.text_freepl_min 15.000000
pmark_dial.txpl.text_freepl_margin 5.000000
pmark_dial.txpl.text_place_en 1
pmark_dial.txpl.text_quarter_en 1
pmark_dial.txpl.text_freepl_min_en 1
pmark_dial.txpl.text_freepl_margin_en 1
pmark_dial.FontAttr.font_name "Arial Narrow"
pmark_dial.FontAttr.text_colour 161
pmark_dial.FontAttr.height 3.000000
pmark_dial.FontAttr.font_enable 1
pmark_dial.FontAttr.text_colour_enable 1
pmark_dial.FontAttr.height_enable 1
pmark_dial.FrameAttr.frame_type 1
pmark_dial.FrameAttr.line_colour 161
pmark_dial.FrameAttr.frame_enable 1
pmark_dial.FrameAttr.line_colour_enable 1
pmark_dial.UnitAttr.Unit 0
pmark_dial.UnitAttr.Precision 0
pmark_dial.UnitAttr.Format 0
pmark_dial.LocationAttributes.DesiredLocationOnPart_enable 1
pmark_dial.LocationAttributes.DesiredLocationOnPart 0
pmark_dial.LocationAttributes.LocationOnPart 0
pmark_dial.LocationAttributes.Orientation_enable 1
pmark_dial.LocationAttributes.AngleRelativeTo 0
pmark_dial.LocationAttributes.Alignment_enable 1
pmark_dial.LocationAttributes.Alignment 0
pmark_dial.LocationAttributes.PlacingFallback_enable 1
pmark_dial.LocationAttributes.PlacingFallback 0
pmark_dial.LocationAttributes.Offset_enable 1
pmark_dial.LocationAttributes.Offset 0.000000
pmark_dial.LocationAttributes.LeaderLineDesired_enable 1
pmark_dial.LocationAttributes.LeaderLineDesired 0
pmark_dial.LocationAttributes.LeaderLineInUse 0
pmark_dial.LocationAttributes.MinimumMarkScale 0.000000
pmark_dial.RebarGroupMarkAttributes.LineType 0
pmark_dial.RebarGroupMarkAttributes.Type 0
pmark_dial.RebarGroupMarkAttributes.TaggedRebarDimMarkLocation 3
pmark_dial.RebarGroupMarkAttributes.CloseRebarDimMarkToFather 0
pmark_dial.RebarGroupMarkAttributes.LineType_en 1
pmark_dial.RebarGroupMarkAttributes.Type_en 1
pmark_dial.RebarGroupMarkAttributes.TaggedRebarDimMarkLocation_en 1
pmark_dial.RebarGroupMarkAttributes.CloseRebarDimMarkToFather_en 1
