csym_dial.in_file "standard"
csym_dial.out_file "section"
csym_dial.label_text "A"
csym_dial.WidthOffset1 9.580000
csym_dial.WidthOffset2 0.620000
csym_dial.LengthOffset 10.000000
csym_dial.ArrowLength 8.000000
csym_dial.ArrowWidth 8.000000
csym_dial.CutLineSide 0
csym_dial.line_colour 164
csym_dial.text_colour 165
csym_dial.fit_symbol 0
csym_dial.aSectionMarkA1 "<< Mark >>"
csym_dial.aSectionMarkA2 "<< Mark >>"
csym_dial.aSectionMarkA3 ""
csym_dial.aSectionMarkA4 ""
csym_dial.aSectionMarkA5 ""
csym_dial.SectionMarkLeftSymbolIndex 184
csym_dial.SectionMarkLeftSymbolSize 5.000000
csym_dial.SectionMarkRightSymbolIndex 183
csym_dial.SectionMarkRightSymbolSize 5.000000
csym_dial.SectionMarkSymbolColor 164
csym_dial.SectionMarkLeftSymbolPositionX 0.000000
csym_dial.SectionMarkLeftSymbolPositionY 0.000000
csym_dial.SectionMarkRightSymbolPositionX 0.000000
csym_dial.SectionMarkRightSymbolPositionY 0.000000
csym_dial.aViewLabelMarkA1 "<< Mark >>"
csym_dial.aViewLabelMarkA2 "<< Mark >>"
csym_dial.aViewLabelMarkA3 ""
csym_dial.aViewLabelMarkA4 ""
csym_dial.aViewLabelMarkA5 ""
csym_dial.ViewLabelMarkSymbolIndex 0
csym_dial.ViewLabelMarkSymbolColor 153
csym_dial.ViewLabelMarkSymbolSize 3.500000
csym_dial.ViewLabelMarkSymbolPositionX 0.000000
csym_dial.ViewLabelMarkSymbolPositionY 0.000000
csym_dial.ViewLabelPosition 1
csym_dial.ViewLabelCustomLength 0.000000
csym_dial.ViewLabelLineLengthType 0
csym_dial.ViewLabelHorizontalPosition 0
csym_dial.SectionMarkA1_en 1
csym_dial.SectionMarkA2_en 1
csym_dial.SectionMarkA3_en 1
csym_dial.SectionMarkA4_en 1
csym_dial.SectionMarkA5_en 1
csym_dial.ViewMarkA1_en 1
csym_dial.ViewMarkA2_en 1
csym_dial.ViewMarkA3_en 1
csym_dial.ViewMarkA4_en 1
csym_dial.ViewMarkA5_en 1
csym_dial.LengthOffset_en 1
csym_dial.WidthOffset1_en 1
csym_dial.WidthOffset2_en 1
csym_dial.ArrowLength_en 1
csym_dial.ArrowWidth_en 1
csym_dial.line_colour_en 1
csym_dial.text_colour_en 1
csym_dial.label_en 1
csym_dial.CutLineSide_en 1
csym_dial.SectionMarkLeftSymbol_en 1
csym_dial.SectionMarkLeftSymbolSize_en 1
csym_dial.SectionMarkRightSymbol_en 1
csym_dial.SectionMarkRightSymbolSize_en 1
csym_dial.ViewLabelMarkSymbolColor_en 1
csym_dial.ViewLabelMarkSymbolSize_en 1
csym_dial.ViewLabelPosition_en 1
csym_dial.ViewLabelMarkSymbolIndex_en 1
csym_dial.SectionMarkLeftSymbolPos_en 1
csym_dial.SectionMarkRightSymbolPos_en 1
csym_dial.ViewLabelMarkSymbolPosX_en 1
csym_dial.ViewLabelMarkSymbolPosY_en 1
csym_dial.SectionMarkLeftSymbolIndex_en 1
csym_dial.SectionMarkRightSymbolIndex_en 1
csym_dial.SectionMarkSymbolColor_en 1
csym_dial.ViewLabelLineLength_en 1
csym_dial.ViewLabelHorizontalPosition_en 1
csym_dial.SectionMarkA1.aInFile " "
csym_dial.SectionMarkA1.aOutFile ""
csym_dial.SectionMarkA1.ContentString "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><Element name="NAME" value="" subType="81"><Format font="Arial Narrow" color="153" height="4.000" hidden="0"/></Element></MarkPart></Mark>"
csym_dial.SectionMarkA1.ShowOn 0
csym_dial.SectionMarkA1.TextPosition 0
csym_dial.SectionMarkA1.TextRotation 1
csym_dial.SectionMarkA1.HorizontalOffset 0.000000
csym_dial.SectionMarkA1.VerticalOffset 0.000000
csym_dial.SectionMarkA1.Alignment 1
csym_dial.SectionMarkA1.Content_en 1
csym_dial.SectionMarkA1.ShowOn_en 1
csym_dial.SectionMarkA1.TextPosition_en 1
csym_dial.SectionMarkA1.HorizontalOffset_en 1
csym_dial.SectionMarkA1.VerticalOffset_en 1
csym_dial.SectionMarkA1.TextRotation_en 1
csym_dial.SectionMarkA1.Alignment_en 1
csym_dial.SectionMarkA1.FontAttr.font_name "Arial Narrow"
csym_dial.SectionMarkA1.FontAttr.text_colour 153
csym_dial.SectionMarkA1.FontAttr.height 4.000000
csym_dial.SectionMarkA1.FontAttr.font_enable 1
csym_dial.SectionMarkA1.FontAttr.text_colour_enable 1
csym_dial.SectionMarkA1.FontAttr.height_enable 1
csym_dial.SectionMarkA1.FrameAttr.frame_type 1
csym_dial.SectionMarkA1.FrameAttr.line_colour 153
csym_dial.SectionMarkA1.FrameAttr.frame_enable 1
csym_dial.SectionMarkA1.FrameAttr.line_colour_enable 1
csym_dial.SectionMarkA2.aInFile ""
csym_dial.SectionMarkA2.aOutFile ""
csym_dial.SectionMarkA2.ContentString "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><Element name="SOURCE_DRAWING_NAME_WHEN_MOVED" value="" subType="25"><Format font="Arial" color="155" height="2.500" hidden="0"/></Element></MarkPart></Mark>"
csym_dial.SectionMarkA2.ShowOn 1
csym_dial.SectionMarkA2.TextPosition 1
csym_dial.SectionMarkA2.TextRotation 1
csym_dial.SectionMarkA2.HorizontalOffset 0.000000
csym_dial.SectionMarkA2.VerticalOffset 0.000000
csym_dial.SectionMarkA2.Alignment 1
csym_dial.SectionMarkA2.Content_en 1
csym_dial.SectionMarkA2.ShowOn_en 1
csym_dial.SectionMarkA2.TextPosition_en 1
csym_dial.SectionMarkA2.HorizontalOffset_en 1
csym_dial.SectionMarkA2.VerticalOffset_en 1
csym_dial.SectionMarkA2.TextRotation_en 1
csym_dial.SectionMarkA2.Alignment_en 1
csym_dial.SectionMarkA2.FontAttr.font_name "romsim"
csym_dial.SectionMarkA2.FontAttr.text_colour 155
csym_dial.SectionMarkA2.FontAttr.height 2.500000
csym_dial.SectionMarkA2.FontAttr.font_enable 1
csym_dial.SectionMarkA2.FontAttr.text_colour_enable 1
csym_dial.SectionMarkA2.FontAttr.height_enable 1
csym_dial.SectionMarkA2.FrameAttr.frame_type 1
csym_dial.SectionMarkA2.FrameAttr.line_colour 155
csym_dial.SectionMarkA2.FrameAttr.frame_enable 1
csym_dial.SectionMarkA2.FrameAttr.line_colour_enable 1
csym_dial.SectionMarkA3.aInFile ""
csym_dial.SectionMarkA3.aOutFile ""
csym_dial.SectionMarkA3.ContentString ""
csym_dial.SectionMarkA3.ShowOn 0
csym_dial.SectionMarkA3.TextPosition 3
csym_dial.SectionMarkA3.TextRotation 0
csym_dial.SectionMarkA3.HorizontalOffset 0.000000
csym_dial.SectionMarkA3.VerticalOffset 0.000000
csym_dial.SectionMarkA3.Alignment 1
csym_dial.SectionMarkA3.Content_en 1
csym_dial.SectionMarkA3.ShowOn_en 1
csym_dial.SectionMarkA3.TextPosition_en 1
csym_dial.SectionMarkA3.HorizontalOffset_en 1
csym_dial.SectionMarkA3.VerticalOffset_en 1
csym_dial.SectionMarkA3.TextRotation_en 1
csym_dial.SectionMarkA3.Alignment_en 1
csym_dial.SectionMarkA3.FontAttr.font_name "romsim"
csym_dial.SectionMarkA3.FontAttr.text_colour 155
csym_dial.SectionMarkA3.FontAttr.height 2.500000
csym_dial.SectionMarkA3.FontAttr.font_enable 1
csym_dial.SectionMarkA3.FontAttr.text_colour_enable 1
csym_dial.SectionMarkA3.FontAttr.height_enable 1
csym_dial.SectionMarkA3.FrameAttr.frame_type 1
csym_dial.SectionMarkA3.FrameAttr.line_colour 155
csym_dial.SectionMarkA3.FrameAttr.frame_enable 1
csym_dial.SectionMarkA3.FrameAttr.line_colour_enable 1
csym_dial.SectionMarkA4.aInFile ""
csym_dial.SectionMarkA4.aOutFile ""
csym_dial.SectionMarkA4.ContentString ""
csym_dial.SectionMarkA4.ShowOn 0
csym_dial.SectionMarkA4.TextPosition 4
csym_dial.SectionMarkA4.TextRotation 0
csym_dial.SectionMarkA4.HorizontalOffset 0.000000
csym_dial.SectionMarkA4.VerticalOffset 0.000000
csym_dial.SectionMarkA4.Alignment 1
csym_dial.SectionMarkA4.Content_en 1
csym_dial.SectionMarkA4.ShowOn_en 1
csym_dial.SectionMarkA4.TextPosition_en 1
csym_dial.SectionMarkA4.HorizontalOffset_en 1
csym_dial.SectionMarkA4.VerticalOffset_en 1
csym_dial.SectionMarkA4.TextRotation_en 1
csym_dial.SectionMarkA4.Alignment_en 1
csym_dial.SectionMarkA4.FontAttr.font_name "romsim"
csym_dial.SectionMarkA4.FontAttr.text_colour 155
csym_dial.SectionMarkA4.FontAttr.height 2.500000
csym_dial.SectionMarkA4.FontAttr.font_enable 1
csym_dial.SectionMarkA4.FontAttr.text_colour_enable 1
csym_dial.SectionMarkA4.FontAttr.height_enable 1
csym_dial.SectionMarkA4.FrameAttr.frame_type 1
csym_dial.SectionMarkA4.FrameAttr.line_colour 155
csym_dial.SectionMarkA4.FrameAttr.frame_enable 1
csym_dial.SectionMarkA4.FrameAttr.line_colour_enable 1
csym_dial.SectionMarkA5.aInFile ""
csym_dial.SectionMarkA5.aOutFile ""
csym_dial.SectionMarkA5.ContentString ""
csym_dial.SectionMarkA5.ShowOn 0
csym_dial.SectionMarkA5.TextPosition 5
csym_dial.SectionMarkA5.TextRotation 0
csym_dial.SectionMarkA5.HorizontalOffset 10.000000
csym_dial.SectionMarkA5.VerticalOffset 0.000000
csym_dial.SectionMarkA5.Alignment 1
csym_dial.SectionMarkA5.Content_en 1
csym_dial.SectionMarkA5.ShowOn_en 1
csym_dial.SectionMarkA5.TextPosition_en 1
csym_dial.SectionMarkA5.HorizontalOffset_en 1
csym_dial.SectionMarkA5.VerticalOffset_en 1
csym_dial.SectionMarkA5.TextRotation_en 1
csym_dial.SectionMarkA5.Alignment_en 1
csym_dial.SectionMarkA5.FontAttr.font_name "romsim"
csym_dial.SectionMarkA5.FontAttr.text_colour 155
csym_dial.SectionMarkA5.FontAttr.height 2.500000
csym_dial.SectionMarkA5.FontAttr.font_enable 1
csym_dial.SectionMarkA5.FontAttr.text_colour_enable 1
csym_dial.SectionMarkA5.FontAttr.height_enable 1
csym_dial.SectionMarkA5.FrameAttr.frame_type 1
csym_dial.SectionMarkA5.FrameAttr.line_colour 155
csym_dial.SectionMarkA5.FrameAttr.frame_enable 1
csym_dial.SectionMarkA5.FrameAttr.line_colour_enable 1
csym_dial.ViewLabelMarkA1.aInFile ""
csym_dial.ViewLabelMarkA1.aOutFile ""
csym_dial.ViewLabelMarkA1.ContentString "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><UserText>SECTION<Format font="Arial Narrow" color="153" height="4.000" hidden="0" override="1"/></UserText></MarkPart><MarkPart groupid="0"><UserText><Format font="Arial Narrow" color="153" height="4.000" hidden="0"/></UserText></MarkPart><MarkPart groupid="0"><Element name="NAME" value="" subType="82"><Format font="Arial Narrow" color="153" height="4.000" hidden="0"/></Element></MarkPart><MarkPart groupid="0"><UserText>-<Format font="Arial Narrow" color="153" height="4.000" hidden="0" override="1"/></UserText></MarkPart><MarkPart groupid="0"><Element name="NAME" value="" subType="82"><Format font="Arial Narrow" color="153" height="4.000" hidden="0"/></Element></MarkPart></Mark>"
csym_dial.ViewLabelMarkA1.ShowOn 0
csym_dial.ViewLabelMarkA1.TextPosition 0
csym_dial.ViewLabelMarkA1.TextRotation 0
csym_dial.ViewLabelMarkA1.HorizontalOffset 0.000000
csym_dial.ViewLabelMarkA1.VerticalOffset 0.000000
csym_dial.ViewLabelMarkA1.Alignment 1
csym_dial.ViewLabelMarkA1.Content_en 1
csym_dial.ViewLabelMarkA1.ShowOn_en 1
csym_dial.ViewLabelMarkA1.TextPosition_en 1
csym_dial.ViewLabelMarkA1.HorizontalOffset_en 1
csym_dial.ViewLabelMarkA1.VerticalOffset_en 1
csym_dial.ViewLabelMarkA1.TextRotation_en 1
csym_dial.ViewLabelMarkA1.Alignment_en 1
csym_dial.ViewLabelMarkA1.FontAttr.font_name "romsim"
csym_dial.ViewLabelMarkA1.FontAttr.text_colour 155
csym_dial.ViewLabelMarkA1.FontAttr.height 2.500000
csym_dial.ViewLabelMarkA1.FontAttr.font_enable 1
csym_dial.ViewLabelMarkA1.FontAttr.text_colour_enable 1
csym_dial.ViewLabelMarkA1.FontAttr.height_enable 1
csym_dial.ViewLabelMarkA1.FrameAttr.frame_type 1
csym_dial.ViewLabelMarkA1.FrameAttr.line_colour 155
csym_dial.ViewLabelMarkA1.FrameAttr.frame_enable 1
csym_dial.ViewLabelMarkA1.FrameAttr.line_colour_enable 1
csym_dial.ViewLabelMarkA2.aInFile "standard"
csym_dial.ViewLabelMarkA2.aOutFile "standard"
csym_dial.ViewLabelMarkA2.ContentString "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><UserText>SCALE:<Format font="Arial Narrow" color="153" height="2.500" hidden="0" override="1"/></UserText></MarkPart><MarkPart groupid="0"><Element name="SCALE" value="" subType="79"><Format font="Arial Narrow" color="153" height="2.500" hidden="0" override="1"/></Element></MarkPart></Mark>"
csym_dial.ViewLabelMarkA2.ShowOn 0
csym_dial.ViewLabelMarkA2.TextPosition 1
csym_dial.ViewLabelMarkA2.TextRotation 0
csym_dial.ViewLabelMarkA2.HorizontalOffset 0.000000
csym_dial.ViewLabelMarkA2.VerticalOffset 0.000000
csym_dial.ViewLabelMarkA2.Alignment 1
csym_dial.ViewLabelMarkA2.Content_en 1
csym_dial.ViewLabelMarkA2.ShowOn_en 1
csym_dial.ViewLabelMarkA2.TextPosition_en 1
csym_dial.ViewLabelMarkA2.HorizontalOffset_en 1
csym_dial.ViewLabelMarkA2.VerticalOffset_en 1
csym_dial.ViewLabelMarkA2.TextRotation_en 1
csym_dial.ViewLabelMarkA2.Alignment_en 1
csym_dial.ViewLabelMarkA2.FontAttr.font_name "Arial Narrow"
csym_dial.ViewLabelMarkA2.FontAttr.text_colour 155
csym_dial.ViewLabelMarkA2.FontAttr.height 2.500000
csym_dial.ViewLabelMarkA2.FontAttr.font_enable 1
csym_dial.ViewLabelMarkA2.FontAttr.text_colour_enable 1
csym_dial.ViewLabelMarkA2.FontAttr.height_enable 1
csym_dial.ViewLabelMarkA2.FrameAttr.frame_type 1
csym_dial.ViewLabelMarkA2.FrameAttr.line_colour 155
csym_dial.ViewLabelMarkA2.FrameAttr.frame_enable 1
csym_dial.ViewLabelMarkA2.FrameAttr.line_colour_enable 1
csym_dial.ViewLabelMarkA3.aInFile ""
csym_dial.ViewLabelMarkA3.aOutFile ""
csym_dial.ViewLabelMarkA3.ContentString ""
csym_dial.ViewLabelMarkA3.ShowOn 0
csym_dial.ViewLabelMarkA3.TextPosition 3
csym_dial.ViewLabelMarkA3.TextRotation 0
csym_dial.ViewLabelMarkA3.HorizontalOffset 0.000000
csym_dial.ViewLabelMarkA3.VerticalOffset 0.000000
csym_dial.ViewLabelMarkA3.Alignment 1
csym_dial.ViewLabelMarkA3.Content_en 1
csym_dial.ViewLabelMarkA3.ShowOn_en 1
csym_dial.ViewLabelMarkA3.TextPosition_en 1
csym_dial.ViewLabelMarkA3.HorizontalOffset_en 1
csym_dial.ViewLabelMarkA3.VerticalOffset_en 1
csym_dial.ViewLabelMarkA3.TextRotation_en 1
csym_dial.ViewLabelMarkA3.Alignment_en 1
csym_dial.ViewLabelMarkA3.FontAttr.font_name "romsim"
csym_dial.ViewLabelMarkA3.FontAttr.text_colour 155
csym_dial.ViewLabelMarkA3.FontAttr.height 2.500000
csym_dial.ViewLabelMarkA3.FontAttr.font_enable 1
csym_dial.ViewLabelMarkA3.FontAttr.text_colour_enable 1
csym_dial.ViewLabelMarkA3.FontAttr.height_enable 1
csym_dial.ViewLabelMarkA3.FrameAttr.frame_type 1
csym_dial.ViewLabelMarkA3.FrameAttr.line_colour 155
csym_dial.ViewLabelMarkA3.FrameAttr.frame_enable 1
csym_dial.ViewLabelMarkA3.FrameAttr.line_colour_enable 1
csym_dial.ViewLabelMarkA4.aInFile ""
csym_dial.ViewLabelMarkA4.aOutFile ""
csym_dial.ViewLabelMarkA4.ContentString ""
csym_dial.ViewLabelMarkA4.ShowOn 0
csym_dial.ViewLabelMarkA4.TextPosition 4
csym_dial.ViewLabelMarkA4.TextRotation 0
csym_dial.ViewLabelMarkA4.HorizontalOffset 0.000000
csym_dial.ViewLabelMarkA4.VerticalOffset 0.000000
csym_dial.ViewLabelMarkA4.Alignment 1
csym_dial.ViewLabelMarkA4.Content_en 1
csym_dial.ViewLabelMarkA4.ShowOn_en 1
csym_dial.ViewLabelMarkA4.TextPosition_en 1
csym_dial.ViewLabelMarkA4.HorizontalOffset_en 1
csym_dial.ViewLabelMarkA4.VerticalOffset_en 1
csym_dial.ViewLabelMarkA4.TextRotation_en 1
csym_dial.ViewLabelMarkA4.Alignment_en 1
csym_dial.ViewLabelMarkA4.FontAttr.font_name "romsim"
csym_dial.ViewLabelMarkA4.FontAttr.text_colour 155
csym_dial.ViewLabelMarkA4.FontAttr.height 2.500000
csym_dial.ViewLabelMarkA4.FontAttr.font_enable 1
csym_dial.ViewLabelMarkA4.FontAttr.text_colour_enable 1
csym_dial.ViewLabelMarkA4.FontAttr.height_enable 1
csym_dial.ViewLabelMarkA4.FrameAttr.frame_type 1
csym_dial.ViewLabelMarkA4.FrameAttr.line_colour 155
csym_dial.ViewLabelMarkA4.FrameAttr.frame_enable 1
csym_dial.ViewLabelMarkA4.FrameAttr.line_colour_enable 1
csym_dial.ViewLabelMarkA5.aInFile ""
csym_dial.ViewLabelMarkA5.aOutFile ""
csym_dial.ViewLabelMarkA5.ContentString ""
csym_dial.ViewLabelMarkA5.ShowOn 0
csym_dial.ViewLabelMarkA5.TextPosition 5
csym_dial.ViewLabelMarkA5.TextRotation 0
csym_dial.ViewLabelMarkA5.HorizontalOffset 10.000000
csym_dial.ViewLabelMarkA5.VerticalOffset 0.000000
csym_dial.ViewLabelMarkA5.Alignment 1
csym_dial.ViewLabelMarkA5.Content_en 1
csym_dial.ViewLabelMarkA5.ShowOn_en 1
csym_dial.ViewLabelMarkA5.TextPosition_en 1
csym_dial.ViewLabelMarkA5.HorizontalOffset_en 1
csym_dial.ViewLabelMarkA5.VerticalOffset_en 1
csym_dial.ViewLabelMarkA5.TextRotation_en 1
csym_dial.ViewLabelMarkA5.Alignment_en 1
csym_dial.ViewLabelMarkA5.FontAttr.font_name "romsim"
csym_dial.ViewLabelMarkA5.FontAttr.text_colour 155
csym_dial.ViewLabelMarkA5.FontAttr.height 2.500000
csym_dial.ViewLabelMarkA5.FontAttr.font_enable 1
csym_dial.ViewLabelMarkA5.FontAttr.text_colour_enable 1
csym_dial.ViewLabelMarkA5.FontAttr.height_enable 1
csym_dial.ViewLabelMarkA5.FrameAttr.frame_type 1
csym_dial.ViewLabelMarkA5.FrameAttr.line_colour 155
csym_dial.ViewLabelMarkA5.FrameAttr.frame_enable 1
csym_dial.ViewLabelMarkA5.FrameAttr.line_colour_enable 1
